### ISSUE TITLE
Invalid relationship in cloud::image::api class

### ISSUE THREAD

**Issue by guits** [enovance/puppet-openstack-cloud#748]
Hello,

currently deploying OS with RH7.0-I.1.3.0 spinalstack release, i encountered a puppet error :

```Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid relationship: File[/etc/ceph/ceph.client.glance.keyring] { require => Ceph::Key[glance] }, because Ceph::Key[glance] doesn't seem to be in the catalog```

the bug seems to be in this part of the code:

https://github.com/enovance/puppet-openstack-cloud/blob/master/manifests/image/api.pp#L202,L209

Guits

**Comment by EmilienM** [comment]
Thanks for your bug report, can you submit it on https://bugs.launchpad.net/puppet-openstack-cloud which is the new place of this module?
Also, I think there is something missing in your Hiera data because it works in our CI (we use Ceph for Glance, Nova & Cinder backends by default).
