### ISSUE TITLE
About OpenStack version

### ISSUE THREAD

**Issue by jiasir** [enovance/puppet-openstack-cloud#749]
Hi, I have a question about OpenStack automation. Should I deploy a Juno version OpenStack using it?

**Comment by EmilienM** [comment]
@jiasir no, this module is supporting Icehouse only. If you want Juno, please use https://github.com/stackforge/puppet-openstack-cloud/

Thanks

**Comment by jiasir** [comment]
@EmilienM https://github.com/stackforge/puppet-openstack-cloud/  If this procject supporint HA environment? I want to deploy a Juno version and HA environment? Can you recommend a way? Many thanks!
